Output demo-b.gif

Set FontSize 16
Set Padding 16
Set Margin 16
Set MarginFill "#8BD5CA"
Set BorderRadius 12
Set Framerate 30
Set Theme "Catppuccin Mocha"
Set FontFamily "Agave Nerd Font"
Set Width 1028
Set Height 512

Hide
Type "go run ./example/main.go"
Enter
Ctrl+L
Sleep 500ms
Show

Set TypingSpeed 150ms
Sleep 1s

Down 3
Sleep 1.5s
Down
Sleep 1s
Left
Sleep 1s
Down 8
Sleep 1s
Left
Sleep 1s
Left
Sleep 1.5s

